/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const CakeOrderInquiry = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'cakeType' : IDL.Text,
  'submittedAt' : Time,
  'phoneNumber' : IDL.Text,
  'specialRequirements' : IDL.Text,
  'servings' : IDL.Nat,
  'eventDate' : IDL.Text,
});
export const CustomerReview = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'createdAt' : Time,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const MenuCategory = IDL.Variant({
  'breads' : IDL.Null,
  'donuts' : IDL.Null,
  'cakes' : IDL.Null,
  'puffs' : IDL.Null,
  'khari' : IDL.Null,
  'cookiesPastries' : IDL.Null,
});
export const MenuItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'category' : MenuCategory,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addCustomerReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'getAllCakeOrderInquiries' : IDL.Func(
      [],
      [IDL.Vec(CakeOrderInquiry)],
      ['query'],
    ),
  'getCustomerReviews' : IDL.Func([], [IDL.Vec(CustomerReview)], ['query']),
  'getMenuByCategory' : IDL.Func(
      [MenuCategory],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'initialize' : IDL.Func([], [], []),
  'submitCakeOrderInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const CakeOrderInquiry = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'cakeType' : IDL.Text,
    'submittedAt' : Time,
    'phoneNumber' : IDL.Text,
    'specialRequirements' : IDL.Text,
    'servings' : IDL.Nat,
    'eventDate' : IDL.Text,
  });
  const CustomerReview = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'createdAt' : Time,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const MenuCategory = IDL.Variant({
    'breads' : IDL.Null,
    'donuts' : IDL.Null,
    'cakes' : IDL.Null,
    'puffs' : IDL.Null,
    'khari' : IDL.Null,
    'cookiesPastries' : IDL.Null,
  });
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'category' : MenuCategory,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'addCustomerReview' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAllCakeOrderInquiries' : IDL.Func(
        [],
        [IDL.Vec(CakeOrderInquiry)],
        ['query'],
      ),
    'getCustomerReviews' : IDL.Func([], [IDL.Vec(CustomerReview)], ['query']),
    'getMenuByCategory' : IDL.Func(
        [MenuCategory],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'initialize' : IDL.Func([], [], []),
    'submitCakeOrderInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };