/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CakeOrderInquiry {
  'id' : bigint,
  'customerName' : string,
  'cakeType' : string,
  'submittedAt' : Time,
  'phoneNumber' : string,
  'specialRequirements' : string,
  'servings' : bigint,
  'eventDate' : string,
}
export interface CustomerReview {
  'id' : bigint,
  'customerName' : string,
  'createdAt' : Time,
  'comment' : string,
  'rating' : bigint,
}
export type MenuCategory = { 'breads' : null } |
  { 'donuts' : null } |
  { 'cakes' : null } |
  { 'puffs' : null } |
  { 'khari' : null } |
  { 'cookiesPastries' : null };
export interface MenuItem {
  'id' : bigint,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'category' : MenuCategory,
  'price' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'addCustomerReview' : ActorMethod<[string, bigint, string], bigint>,
  'getAllCakeOrderInquiries' : ActorMethod<[], Array<CakeOrderInquiry>>,
  'getCustomerReviews' : ActorMethod<[], Array<CustomerReview>>,
  'getMenuByCategory' : ActorMethod<[MenuCategory], Array<MenuItem>>,
  'getMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'initialize' : ActorMethod<[], undefined>,
  'submitCakeOrderInquiry' : ActorMethod<
    [string, string, string, string, bigint, string],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];